// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('schoolDairy').controller('ScheduleCtrl', function($scope, schedule) {
    $scope.schedule = schedule;
    $scope.loading = true;
    return schedule.load().then(function() {
      return $scope.loading = false;
    }, function() {
      return $scope.loading = false;
    });
  });

}).call(this);
